---
# tasks file for ruby
- name: Install dependencies packages for ruby
  become: yes # sudoで実行
  yum:
    name: "{{ ruby_dependencies_pkg }}"
    state: present # インストールされている場合はスキップ

- name: SetUp rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv

- name: SetUp rbenv path
  become: yes
  template:
    src: roles/ruby/templates/rbenv_system.sh.j2 # .j2 ファイルを指定すること
    dest: /etc/profile.d/rbenv_system.sh
    owner: root
    group: root
    mode: 0755

- name: SetUp ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: Install specific ruby version
  shell: bash -lc "CONFIGURE_OPTS=\"--disable-install-doc\" rbenv install --skip-existing 3.1.2" # -lc 環境変数読み込みオプション

- name: Set global ruby version
  shell: bash -lc "rbenv global 3.1.2"


